/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CovidAlert {
        "body": string;
        "heading": string;
        "linkHref"?: string;
        "linkText"?: string;
    }
    interface CovidPost {
        "host": string;
        "postExcerpt": string;
        "postLink": string;
        "postMediaId"?: number;
        "postTitle": string;
    }
    interface CovidPosts {
        "host": string;
    }
    interface LoadingSpinner {
    }
}
declare global {
    interface HTMLCovidAlertElement extends Components.CovidAlert, HTMLStencilElement {
    }
    var HTMLCovidAlertElement: {
        prototype: HTMLCovidAlertElement;
        new (): HTMLCovidAlertElement;
    };
    interface HTMLCovidPostElement extends Components.CovidPost, HTMLStencilElement {
    }
    var HTMLCovidPostElement: {
        prototype: HTMLCovidPostElement;
        new (): HTMLCovidPostElement;
    };
    interface HTMLCovidPostsElement extends Components.CovidPosts, HTMLStencilElement {
    }
    var HTMLCovidPostsElement: {
        prototype: HTMLCovidPostsElement;
        new (): HTMLCovidPostsElement;
    };
    interface HTMLLoadingSpinnerElement extends Components.LoadingSpinner, HTMLStencilElement {
    }
    var HTMLLoadingSpinnerElement: {
        prototype: HTMLLoadingSpinnerElement;
        new (): HTMLLoadingSpinnerElement;
    };
    interface HTMLElementTagNameMap {
        "covid-alert": HTMLCovidAlertElement;
        "covid-post": HTMLCovidPostElement;
        "covid-posts": HTMLCovidPostsElement;
        "loading-spinner": HTMLLoadingSpinnerElement;
    }
}
declare namespace LocalJSX {
    interface CovidAlert {
        "body"?: string;
        "heading"?: string;
        "linkHref"?: string;
        "linkText"?: string;
    }
    interface CovidPost {
        "host"?: string;
        "postExcerpt"?: string;
        "postLink"?: string;
        "postMediaId"?: number;
        "postTitle"?: string;
    }
    interface CovidPosts {
        "host"?: string;
    }
    interface LoadingSpinner {
    }
    interface IntrinsicElements {
        "covid-alert": CovidAlert;
        "covid-post": CovidPost;
        "covid-posts": CovidPosts;
        "loading-spinner": LoadingSpinner;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "covid-alert": LocalJSX.CovidAlert & JSXBase.HTMLAttributes<HTMLCovidAlertElement>;
            "covid-post": LocalJSX.CovidPost & JSXBase.HTMLAttributes<HTMLCovidPostElement>;
            "covid-posts": LocalJSX.CovidPosts & JSXBase.HTMLAttributes<HTMLCovidPostsElement>;
            "loading-spinner": LocalJSX.LoadingSpinner & JSXBase.HTMLAttributes<HTMLLoadingSpinnerElement>;
        }
    }
}
