name: Publish to NPM

on:
  push:
    branches:
      - main

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/
      - run: yarn install
      - run: yarn build
      - name: Upload dist files
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist
      - name: Upload loader files
        uses: actions/upload-artifact@v2
        with:
          name: loader
          path: loader

  publish:
    name: Publish
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/
      - name: Download dist files from build
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist
      - name: Download loader files from build
        uses: actions/download-artifact@v2
        with:
          name: loader
          path: loader
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
